### ISSUE TITLE
missing directory

### ISSUE THREAD

**Issue by d-rep** [javebratt/ionic-firebase-auth#1]
Running `ionic serve` with v1.7.15 on this project results in the following error:

```
"www" directory cannot be found. Please make sure the working directory is an Ionic project.
There was an error serving your Ionic application: "www" directory cannot be found. Please make sure the working directory is an Ionic project.
```

**Comment by korderos** [comment]
You have to run ionic from the directory of the project, the one that contain the www folder.
So first, "cd myproject" and after "ionic serve"

**Comment by javebratt** [comment]
Hi @d-rep how did you start the app? Did you clone this project or did you use it as a template?

The correct way of using it is as a template, you open your terminal and go to your projects folder and there you type:

`ionic start myApp https://github.com/javebratt/ionic-firebase-auth/`

after that you cd into the myApp folder and there you can run ionic serve.

When you create the app this way Ionic's CLI will take care of everything :)

Let me know if you have any other problems.

If I don't here from you soon I'll asume that was the problem and close the issue.

Cheers

**Comment by d-rep** [comment]
Yeah that was my exact issue, where I didn't realize that `git clone` wouldn't work here.  Thanks @javebratt and sorry I missed that in the README

**Comment by javebratt** [comment]
No problem, happy to see people are finding this useful :smile:
